#ifndef IO_MAP_H
#define IO_MAP_H

//* LOADCELLS
#define LOADCELL1_DOUT_PIN 9
#define LOADCELL1_SCK_PIN 8
#define LOADCELL2_DOUT_PIN 15
#define LOADCELL2_SCK_PIN 14
#define LOADCELL3_DOUT_PIN 1
#define LOADCELL3_SCK_PIN 0

#define SD_CS_PIN 17
#define SD_MOSI_PIN 19
#define SD_MISO_PIN 16
#define SD_SCK_PIN 18

//* RS-485
#define WRITE_RS_PIN 12
#define READ_RS_PIN 13
#define ENABLE_RS_PIN 20

#endif  // IO_MAP_H