#ifndef IO_MAP_H
#define IO_MAP_H

//* LOADCELLS
#define LIFT_THRUST_DOUT1_PIN 3
#define LIFT_THRUST_SCK1_PIN 2
#define LIFT_THRUST_DOUT2_PIN 9
#define LIFT_THRUST_SCK2_PIN 8
#define LIFT_THRUST_DOUT3_PIN 15
#define LIFT_THRUST_SCK3_PIN 14

#define SD_CS_PIN 17

//* RS-485
#define WRITE_RS_PIN 0
#define READ_RS_PIN 1

#endif  // IO_MAP_H